package VTC_Introduce_Programming.lab_1;

import java.util.Scanner;

public class Lab1_1 {
    public static void main(String[] args) {
        System.out.println("Vui lòng nhập thông tin");
        //String hoten;
        //String name;
        //String sex;
        //float height;
        //int weight;
        //String country;
        //String chuyennganh;
        //float diemtb;
        Scanner scanner = new Scanner(System.in);
        System.out.println("thông tin ứng viên 1");
        System.out.println("Nhập họ tên:");
        String hoten = scanner.nextLine();
        System.out.println("Nhập năm sinh");
        String year = scanner.nextLine();
        System.out.println("nhập giới tính:");
        String sex = scanner.nextLine();
        System.out.println("nhập chiểu cao");
        int height = scanner.nextInt();
        System.out.println("Nhập cân nặng");
        int weight = scanner.nextInt();
        scanner.nextLine();
        System.out.println("Nhập quê quán:");
        String country = scanner.nextLine();
        System.out.println("Nhập chuyên ngành:");
        String chuyennganh = scanner.nextLine();
        System.out.println("Nhập điểm trung bình");
        float diemtb = scanner.nextInt();
        scanner.nextLine();
        System.out.println("thông tin ứng viên 2");
        System.out.println("Nhập họ tên:");
        String hotenq = scanner.nextLine();
        System.out.println("Nhập năm sinh");
        String yearq = scanner.nextLine();
        System.out.println("nhập giới tính:");
        String sexq = scanner.nextLine();
        System.out.println("nhập chiểu cao");
        int heightq = scanner.nextInt();
        System.out.println("Nhập cân nặng");
        int weightq = scanner.nextInt();
        scanner.nextLine();
        System.out.println("Nhập quê quán:");
        String countryq = scanner.nextLine();
        System.out.println("Nhập chuyên ngành:");
        String chuyennganhq = scanner.nextLine();
        System.out.println("Nhập điểm trung bình");
        float diemtbq = scanner.nextInt();
        scanner.nextLine();
        System.out.println("thông tin ứng viên 3");
        System.out.println("Nhập họ tên:");
        String hotenw = scanner.nextLine();
        System.out.println("Nhập năm sinh");
        String yearw = scanner.nextLine();
        System.out.println("nhập giới tính:");
        String sexw = scanner.nextLine();
        System.out.println("nhập chiểu cao");
        int heightw = scanner.nextInt();
        System.out.println("Nhập cân nặng");
        int weightw = scanner.nextInt();
        scanner.nextLine();
        System.out.println("Nhập quê quán:");
        String countryw = scanner.nextLine();
        System.out.println("Nhập chuyên ngành:");
        String chuyennganhw = scanner.nextLine();
        System.out.println("Nhập điểm trung bình");
        float diemtbw = scanner.nextInt();

        System.out.println("Chương trình nhập xuất thông tin Ứng viên");
        System.out.println("============================================");
        System.out.println("Thông tin Ứng viên 1:");
        System.out.println("Họ và tên:" + hoten);
        System.out.println("Năm sinh:" + year);
        System.out.println("Giới tính:" + sex);
        System.out.println("Chiều cao:" + weight);
        System.out.println("Cân nặng:" + weight);
        System.out.println("Quên Quán:" + country);
        System.out.println("Chuyên Ngành:" + chuyennganh);
        System.out.println("Điểm Trung Bình:" + diemtb);
        System.out.println("Thông tin Ứng viên 2:");
        System.out.println("Họ và tên:" + hotenq);
        System.out.println("Năm sinh:" + yearq);
        System.out.println("Giới tính:" + sexq);
        System.out.println("Chiều cao:" + weightq);
        System.out.println("Cân nặng:" + weightq);
        System.out.println("Quên Quán:" + countryq);
        System.out.println("Chuyên Ngành:" + chuyennganhq);
        System.out.println("Điểm Trung Bình:" + diemtbq);
        System.out.println("Thông tin Ứng viên 3:");
        System.out.println("Họ và tên:" + hotenw);
        System.out.println("Năm sinh:" + yearw);
        System.out.println("Giới tính:" + sexw);
        System.out.println("Chiều cao:" + weightw);
        System.out.println("Cân nặng:" + weightw);
        System.out.println("Quên Quán:" + countryw);
        System.out.println("Chuyên Ngành:" + chuyennganhw);
        System.out.println("Điểm Trung Bình:" + diemtbw);
    }
}
