package VTC_Introduce_Programming.lab_1;

import java.util.Scanner;

public class lab2_2 {
    public static void main(String[] args) {
        System.out.println("Danh sách thông tin ứng viên 1 ");
        Scanner sc = new Scanner(System.in);
        System.out.println("Nhập STT");
        int STT = sc.nextInt();
        sc.nextLine();
        System.out.println("Nhập họ và tên");
        String Hoten = sc.nextLine();
        System.out.println("N.sinh");
        int year = sc.nextInt();
        sc.nextLine();
        System.out.println("nhập giới tinh");
        String sex = sc.nextLine();
        System.out.println("Nhập chiều cao");
        double height = sc.nextDouble();
        System.out.println("Nhập cân nặng");
        int weight = sc.nextInt();
        sc.nextLine();
        System.out.println("Nhập quê quán");
        String city = sc.nextLine();
        System.out.println("Nhập chuyên ngành");
        String job = sc.nextLine();
        System.out.println("Nhập điểm trung bình");
        double diem = sc.nextDouble();
        System.out.println("Danh sách thông tin ứng viên 2 ");
        System.out.println("Nhập STT");
        int STTq = sc.nextInt();
        sc.nextLine();
        System.out.println("Nhập họ và tên");
        String Hotenq = sc.nextLine();
        System.out.println("N.sinh");
        int yearq = sc.nextInt();
        sc.nextLine();
        System.out.println("nhập giới tinh");
        String sexq = sc.nextLine();
        System.out.println("Nhập chiều cao");
        double heightq = sc.nextDouble();
        System.out.println("Nhập cân nặng");
        int weightq = sc.nextInt();
        sc.nextLine();
        System.out.println("Nhập quê quán");
        String cityq = sc.nextLine();
        System.out.println("Nhập chuyên ngành");
        String jobq = sc.nextLine();
        System.out.println("Nhập điểm trung bình");
        double diemq = sc.nextDouble();
        System.out.println("Danh sách thông tin ứng viên 3 ");
        System.out.println("Nhập STT");
        int STTw = sc.nextInt();
        sc.nextLine();
        System.out.println("Nhập họ và tên");
        String Hotenw = sc.nextLine();
        System.out.println("N.sinh");
        int yearw = sc.nextInt();
        sc.nextLine();
        System.out.println("nhập giới tinh");
        String sexw = sc.nextLine();
        System.out.println("Nhập chiều cao");
        double heightw = sc.nextDouble();
        System.out.println("Nhập cân nặng");
        int weightw = sc.nextInt();
        sc.nextLine();
        System.out.println("Nhập quê quán");
        String cityw = sc.nextLine();
        System.out.println("Nhập chuyên ngành");
        String jobw = sc.nextLine();
        System.out.println("Nhập điểm trung bình");
        double diemw = sc.nextDouble();
        System.out.println("STT" + "\t" + "Ho ten" + "\t" + "\t" + "\t" + "N.sinh" + "\t" + "G.tinh" + "\t" + "C.cao" + "\t" + "C.nang" + "\t" + "Que quan" + "\t" + "\t" + "C.ngành" + "\t" + "\t" + "DTB");
        System.out.println("===================================================================================");
        System.out.println(STT + "\t" + Hoten + "\t"  + year + "\t" + sex + "\t" + "\t" + height + "\t" + weight + "\t" + "\t" + city + "\t"  + job + "\t" + diem);
        System.out.println(STTq + "\t" + Hotenq + "\t" + "\t"  + yearq + "\t" + sexq + "\t" + "\t" + heightq + "\t" + weightq + "\t" + "\t" + cityq + "\t" + "\t" + "\t"  + jobq + "\t"  + diemq);
        System.out.println(STTw + "\t" + Hotenw + "\t" + "\t"  + yearw + "\t" + sexw + "\t" + "\t" + heightw + "\t" + weightw + "\t" + "\t" + cityw + "\t" + "\t"  + jobw + "\t" + "\t" + diemw);
    }
}
